services:
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
    depends_on:
      - db
      - redis

  app:
    build: .
    environment:
      - RAILS_ENV=development
    depends_on:
      - db
      - redis
      - sidekiq
      - mailcatcher
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
    command: >
      sh -c "(bundle check || bundle install) && bundle exec rails db:prepare && bundle exec rails assets:precompile && bundle exec rails -s -p 3000 -b '0.0.0.0'"

volumes:
  bundler_gems: