services:
  db:
    image: postgres:10.14
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgressql/data
    ports:
      - "5432:5432"
  
  redis:
    image: redis:5.0.4
    restart: unless-stopped
    ports:
      - "6379:6379"

  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.8.2
    ports:
    - "1080:1080"
    - "1025:1025"